-- Every lesson of a course is reachable from the day the student enrols. The
-- only gate left is the final exam, which `resolveGate` derives from
-- `courses.exam_lesson_id` — so the per-course release mode has nothing left
-- to say and is removed rather than left as a column that reads as if it did.
--
-- Why it went, in one sentence: the chain it drove gated lecture N+1 on
-- `lesson_progress.state` for lecture N, and that column records whether the
-- student pressed «خلاص · التالي» — not whether they watched anything. So it
-- showed the identical padlock to the student who had done the work and the
-- student who had not, and the padlock's dialog then pointed at the lecture
-- they were already sitting on. See `gate-rule.ts` for the full reasoning and
-- for why the exam is the one thing still closed.
--
-- ⚠️ Safe to DROP rather than to deprecate-then-drop, and the reason is the
-- deploy topology rather than the fact that this lands in the same commit as
-- the code that stopped reading it.
--
-- `apps/api/docker-entrypoint.sh` runs `migrate deploy` on every boot, from
-- inside the NEW image, and `docker-compose.yml` declares one `api` service
-- with no replicas — so the old container is gone before this statement runs.
-- There is no moment at which a server still selecting `progression_mode` is
-- talking to a database that no longer has it.
--
-- That would stop being true the day the api scales past one replica or gains
-- a rolling update: two containers overlap, the new one migrates, and every
-- request the old one serves through `PlayerService.outline` fails on a
-- missing column. A drop like this would then have to be split in two — ship
-- the code that stops reading it, deploy, then drop in a later release.
--
-- Dropping it is also what makes the change permanent: a course row that can
-- still say `sequential` is a lock waiting to come back on.
ALTER TABLE app.courses DROP COLUMN IF EXISTS progression_mode;

-- The type is used by nothing else (it was declared for this column alone), so
-- it goes with it. `IF EXISTS` on both statements so re-running the migration
-- against an already-migrated database is a no-op rather than an error.
DROP TYPE IF EXISTS app.progression_mode;
