// GENERATED BY scripts/sync-mobile-validation.ts — DO NOT EDIT.
//
// These are not transcriptions. Each string below was produced by RUNNING the
// zod schema in packages/contracts against invalid input and reading the issue
// back, so it is byte-identical to what a student sees on the web.
//
// Run `pnpm mobile:validation` after changing any schema in
// packages/contracts/src/auth.ts or onboarding.ts.
//
// ignore_for_file: lines_longer_than_80_chars

/// Field-level validation messages, mirrored from the shared zod schemas.
///
/// ⚠️ These live in the SCHEMAS, not in the copy table, because a message and
/// the rule that produces it have to change together. That is why they are not
/// in [CopyKeys] and are not translated by easy_localization — there is no key
/// to look up.
abstract final class ValidationMessages {
  /// The one sign-in field, left empty.
  static const String loginIdentifierRequired = "رقم موبايلك أو إيميلك";

  /// Sign-in password, left empty. Note there is NO minimum length on sign-in — see the schema.
  static const String loginPasswordRequired = "كلمة المرور مطلوبة";

  /// Full name under 2 characters.
  static const String registerNameRequired = "الاسم الكامل مطلوب";

  /// Full name over 120 characters.
  static const String registerNameTooLong = "الاسم طويل جدًا";

  /// Phone left empty. The account identity — see EgyptianPhone.
  static const String registerPhoneRequired = "رقم الموبايل مطلوب";

  /// Phone that is not a valid Egyptian number. Same constant as EgyptianPhone.invalidMessage.
  static const String registerPhoneInvalid = "رقم الهاتف يجب أن يكون رقمًا مصريًا صحيحًا";

  /// A non-empty but malformed optional email. Blank is ACCEPTED — the field is optional.
  static const String registerEmailInvalid = "أدخل بريدًا إلكترونيًا صحيحًا";

  /// Under MIN_PASSWORD_LENGTH (8), which is better-auth’s own default.
  static const String registerPasswordTooShort = "كلمة المرور لازم تكون 8 أحرف على الأقل";

  /// Over MAX_PASSWORD_LENGTH (128).
  static const String registerPasswordTooLong = "كلمة المرور طويلة جدًا";

  /// Confirm-password left empty.
  static const String registerConfirmRequired = "تأكيد كلمة المرور مطلوب";

  /// The two passwords differ. Attached to confirmPassword by a superRefine, not to password.
  static const String registerConfirmMismatch = "كلمتا المرور غير متطابقتين";

  /// The onboarding wizard, keyed by field path.
  ///
  /// Discovered by parsing an empty object rather than probed field by field:
  /// onboarding grows a field every time the taxonomy does, and a hand-written
  /// list would go stale silently.
  static const Map<String, String> onboarding = <String, String>{
    "fatherPhone": "هاتف الأب مطلوب",
    "fullName": "الاسم الكامل مطلوب",
    "governorateCode": "لازم نحدد المحافظة",
    "phone": "رقم الهاتف مطلوب",
    "schoolName": "اسم المدرسة مطلوب",
    "year": "لازم نحدد الصف الدراسي",
  };
}
