/**
 * The single Arabic string table. No component may contain a user-facing literal.
 * This is what makes adding English later a routing change rather than a rewrite.
 */
export const copy = {
  site: {
    name: 'أيمن أبو العيلة',
    tagline: 'البرمجة وعلوم الحاسب — نظام البكالوريا المصرية',
    instructor: 'المهندس أيمن أبو العيلة',
  },
  nav: {
    home: 'الرئيسية',
    courses: 'الكورسات',
    about: 'عن المنصة',
    contact: 'تواصل معنا',
    login: 'تسجيل الدخول',
    register: 'حساب جديد',
    dashboard: 'حسابي',
  },
  theme: {
    toggle: 'تبديل المظهر',
    light: 'فاتح',
    dark: 'داكن',
    system: 'حسب النظام',
  },
  onboarding: {
    title: 'أكمل بيانات حسابك',
    subtitle: 'محتاجين شوية معلومات بسيطة عشان نظبطلك المنصة على مقاسك',
    step1Title: 'من إنت',
    step2Title: 'مكانك',
    step3Title: 'دراستك',
    optionalTitle: 'بيانات إضافية',
    optionalSubtitle: 'اختيارية دلوقتي، وهنفكرك بيها تاني بعد كده',
    fullName: 'الاسم الكامل',
    fullNamePlaceholder: 'اكتب اسمك بالكامل',
    gender: 'النوع',
    genderPlaceholder: 'اختر النوع',
    genderMale: 'ذكر',
    genderFemale: 'أنثى',
    genderError: 'اختر النوع',
    phone: 'رقم الهاتف',
    phonePlaceholder: '01012345678',
    governorate: 'المحافظة',
    governoratePlaceholder: 'اختر محافظتك',
    schoolName: 'اسم المدرسة',
    schoolNamePlaceholder: 'اختياري',
    system: 'النظام الدراسي',
    systemPlaceholder: 'اختر النظام الدراسي',
    year: 'الصف الدراسي',
    yearPlaceholder: 'اختر الصف الدراسي',
    track: 'المسار',
    trackPlaceholder: 'اختر المسار',
    electiveSubject: 'المادة الاختيارية',
    electiveSubjectPlaceholder: 'اختر المادة الاختيارية',
    fatherPhone: 'رقم هاتف الأب',
    motherPhone: 'رقم هاتف الأم',
    parentPhonePlaceholder: 'اختياري',
    skip: 'تخطي دلوقتي',
    skipHint: 'هنسألك تاني بعدين',
    undoSkip: 'إظهار الحقول',
    submit: 'حفظ ومتابعة',
    submitPending: 'جارٍ الحفظ…',
    submitError: 'تعذر حفظ بياناتك. تأكد منها وحاول تاني.',
    phoneConflictError: 'رقم الهاتف ده مسجل بحساب تاني بالفعل',
  },
  auth: {
    login: {
      title: 'تسجيل الدخول',
      subtitle: 'أهلًا بيك تاني، سجّل دخولك للمتابعة',
    },
    register: {
      title: 'إنشاء حساب جديد',
      subtitle: 'اعمل حسابك وابدأ رحلتك في البكالوريا المصرية',
    },
    fields: {
      name: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
    },
    actions: {
      login: 'تسجيل الدخول',
      loginPending: 'جارٍ تسجيل الدخول…',
      register: 'إنشاء حساب',
      registerPending: 'جارٍ إنشاء الحساب…',
    },
    switch: {
      noAccount: 'لسه معملتش حساب؟',
      createAccount: 'إنشاء حساب جديد',
      haveAccount: 'عندك حساب بالفعل؟',
      login: 'تسجيل الدخول',
    },
    providers: {
      divider: 'أو',
      google: 'المتابعة عبر جوجل',
      apple: 'المتابعة عبر أبل',
    },
    errors: {
      // One generic message per form, shown for EVERY failure reason on that
      // form (wrong password, unknown email, locked account, network error,
      // provider error). Never distinguish the cause in the UI — S1 requires
      // the login endpoint's responses to already be byte-identical across
      // failure modes, and a "helpful" UI message would quietly undo that by
      // reintroducing an enumeration signal one layer up.
      login: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      register: 'تعذر إنشاء الحساب. تأكد من البيانات وحاول تاني.',
    },
  },
  common: {
    loading: 'جارٍ التحميل',
    error: 'حصل خطأ',
    retry: 'حاول تاني',
    empty: 'مفيش حاجة هنا لسه',
    // Plan 6 append.
    undo: 'تراجع',
  },
  settings: {
    devices: {
      title: 'أجهزتي',
      subtitle: 'الأجهزة اللي سجلت دخولك منها. تقدر تلغي أي جهاز مش عارفه.',
      current: 'الجهاز الحالي',
      loggedInAt: 'دخلت من هنا في',
      lastSeenAt: 'آخر نشاط',
      revoke: 'إلغاء الجهاز',
      revokePending: 'جارٍ الإلغاء…',
      revokeCurrentConfirm: 'ده الجهاز اللي بتستخدمه دلوقتي. لو ألغيته هتتسجل خروجك فورًا. متأكد؟',
      revokeError: 'تعذر إلغاء الجهاز. حاول تاني.',
      empty: 'مفيش أجهزة مسجلة دخول دلوقتي',
    },
  },
  home: {
    eyebrow: '01 / المنصة',
  },
  catalog: {
    eyebrow: '03 / الكورسات',
    title: 'الكورسات',
    subtitle: 'كل محاضرات البرمجة وعلوم الحاسب، مرتبة بالصف والمسار',
    empty: 'مفيش كورسات منشورة لسه',
    lessonCount: 'محاضرة',
    duration: 'المدة',
    minutes: 'دقيقة',
    hours: 'ساعة',
    freePreview: 'معاينة مجانية',
    free: 'مجاني',
    open: 'افتح الكورس',
  },
  course: {
    breadcrumbHome: 'الرئيسية',
    breadcrumbCatalog: 'الكورسات',
    content: 'محتوى الكورس',
    about: 'عن الكورس',
    instructor: 'المُحاضر',
    start: 'ابدأ الكورس',
    continue: 'كمّل الكورس',
    enrolled: 'إنت مشترك في الكورس ده',
    notFound: 'الكورس ده مش موجود',
    lessonKind: {
      video: 'فيديو',
      quiz: 'اختبار',
      attachment: 'مرفق',
      text: 'قراءة',
    },
  },
  player: {
    eyebrow: '09 / المشغّل',
    outline: 'محتوى الكورس',
    previous: 'الدرس السابق',
    next: 'الدرس التالي',
    markComplete: 'أنهيت الدرس · التالي',
    markCompleteFinal: 'أنهيت الدرس',
    marking: 'بنسجّل…',
    completed: 'تم',
    inProgress: 'جارٍ',
    notStarted: 'لسه',
    play: 'شغّل الفيديو',
    videoUnavailable: 'الفيديو مش متاح دلوقتي',
    attachments: 'الملفات المرفقة',
    download: 'تحميل',
    quizIntro: 'الدرس ده اختبار. ابدأ لما تكون جاهز.',
    quizCta: 'ابدأ الاختبار',
    courseProgress: 'تقدّمك في الكورس',
    lessonsCompleted: 'درس مكتمل من',
    autoCompleteHint: 'الدرس بيتحسب لوحده لما توصل لآخر الفيديو وتكون شُفت معظمه.',
    manualOnlyHint: 'مدة الفيديو مش متسجّلة، فاضغط «أنهيت الدرس» لما تخلّص.',
    saveFailed: 'مش قادرين نسجّل تقدّمك دلوقتي',
  },
  dashboard: {
    eyebrow: '01 / حسابي',
    title: 'حسابي',
    continueWatching: 'أكمل من حيث وقفت',
    continueCta: 'كمّل',
    remaining: 'باقي',
    myCourses: 'كورساتي',
    recentScores: 'آخر النتائج',
    noScoresYet: 'لسه مفيش نتائج. أول اختبار تخلّصه هيظهر هنا.',
    noCoursesYet: 'لسه مش مشترك في أي كورس.',
    browseCourses: 'اتفرّج على الكورسات',
  },
  enrollment: {
    enroll: 'اشترك في الكورس',
    enrolled: 'أنت مشترك',
    enrolling: 'بنشتركك…',
    startCourse: 'ابدأ الكورس',
  },
  admin: {
    nav: {
      dashboard: 'لوحة التحكم',
      content: 'المحتوى',
      courses: 'الكورسات',
      questions: 'بنك الأسئلة',
      appeals: 'التظلمات',
      // ── Plan 6 appends below. Plan 3 owns this sub-namespace; entries are
      // ADDED here, never rewritten, or every existing admin link breaks.
      overview: 'نظرة عامة',
      students: 'الطلبة',
      attempts: 'المحاولات',
      taxonomy: 'الهيكل الدراسي',
      home: 'الصفحة الرئيسية',
      navigation: 'القوائم',
      branding: 'الهوية البصرية',
      flags: 'خصائص التشغيل',
      media: 'مكتبة الوسائط',
      audit: 'سجل النشاط',
      settings: 'الإعدادات',
    },
    common: {
      create: 'إضافة',
      save: 'حفظ',
      saving: 'جارٍ الحفظ',
      saved: 'اتحفظ',
      saveFailed: 'الحفظ فشل — التغييرات اترجعت زي ما كانت',
      cancel: 'إلغاء',
      close: 'إغلاق',
      delete: 'حذف',
      deleteConfirm: 'متأكد؟ الإجراء ده مش هيترجع.',
      required: 'الحقل ده مطلوب',
      publish: 'نشر',
    },
    course: {
      listTitle: 'الكورسات',
      new: 'كورس جديد',
      title: 'اسم الكورس',
      edit: 'تعديل الكورس',
      slug: 'المُعرّف في الرابط',
      slugHint: 'حروف إنجليزي صغيرة وأرقام وشرطات — ده اللي بيظهر في العنوان',
      subtitle: 'وصف مختصر',
      description: 'الوصف',
      system: 'النظام الدراسي',
      year: 'الصف الدراسي',
      track: 'المسار',
      trackNoneYear1: 'الصف الأول مالوش مسار',
      subject: 'المادة',
      subjectEmpty: 'مفيش مواد متاحة للاختيار ده — جرّب نظام أو صف أو مسار تاني',
      status: 'الحالة',
      statusDraft: 'مسودة',
      statusPublished: 'منشور',
      statusArchived: 'مؤرشف',
      publish: 'نشر',
      unpublish: 'رجّعه مسودة',
      publishBlocked: 'لازم يكون فيه محاضرة منشورة واحدة على الأقل',
      empty: 'مفيش كورسات لسه',
    },
    section: {
      new: 'قسم جديد',
      title: 'اسم القسم',
      summary: 'نبذة',
      empty: 'مفيش أقسام لسه',
    },
    lesson: {
      new: 'محاضرة جديدة',
      title: 'عنوان المحاضرة',
      kind: 'النوع',
      freePreview: 'معاينة مجانية',
      estimatedSeconds: 'المدة التقديرية بالثواني',
      videoUrl: 'رابط يوتيوب',
      videoUrlHint: 'بناخد كود الفيديو (11 حرف) بس — الباقي بيتشال ومحدش بيفتح الرابط',
      videoUrlInvalid: 'الرابط ده مش رابط يوتيوب صالح',
      durationSeconds: 'مدة الفيديو بالثواني',
      body: 'محتوى الدرس',
      empty: 'مفيش محاضرات في القسم ده',
    },
    reorder: {
      hint: 'اسحب لإعادة الترتيب، أو استخدم زر المسافة والأسهم من الكيبورد',
      handle: 'مقبض السحب',
      pickedUp: 'اتمسكت المحاضرة في الترتيب رقم',
      movedOver: 'بقت في الترتيب رقم',
      dropped: 'اتسابت في الترتيب رقم',
      cancelled: 'اتلغى السحب والترتيب رجع زي ما كان',
    },
    // ── Plan 6 owns everything from here down inside `admin` ───────────────
    title: 'لوحة التحكم',
    signedInAs: 'داخل باسم',
    openMenu: 'فتح القائمة',
    overviewLead: 'كل حاجة في الموقع بتتظبط من هنا.',
    actions: {
      save: 'حفظ',
      saving: 'جارٍ الحفظ',
      saved: 'تم الحفظ',
      cancel: 'إلغاء',
      undo: 'تراجع',
      delete: 'حذف',
      archive: 'أرشفة',
      restore: 'استرجاع',
      publish: 'نشر',
      unpublish: 'إلغاء النشر',
      create: 'إضافة',
      edit: 'تعديل',
      confirm: 'تأكيد',
    },
    settings: {
      title: 'إعدادات المنصة',
      sectionBranding: 'الهوية البصرية',
      sectionSeo: 'بيانات محركات البحث',
      sectionContact: 'وسائل التواصل',
      accent: 'اللون الأساسي',
      radius: 'حدة الحواف',
      logoLight: 'الشعار — الوضع الفاتح',
      logoDark: 'الشعار — الوضع الداكن',
      favicon: 'أيقونة الموقع',
      seoTitle: 'عنوان الموقع',
      seoDescription: 'وصف الموقع',
      email: 'البريد الإلكتروني',
      phone: 'رقم الهاتف',
      whatsapp: 'واتساب',
      facebook: 'فيسبوك',
      youtube: 'يوتيوب',
      telegram: 'تليجرام',
    },
    branding: {
      title: 'الهوية البصرية',
      lead: 'الألوان بتتختار من مجموعة جاهزة — مفيش كتابة ألوان بإيدك.',
      accentAmber: 'كهرماني',
      accentCyan: 'سماوي',
      accentBlue: 'أزرق',
      accentViolet: 'بنفسجي',
      accentMagenta: 'أرجواني',
      accentSlate: 'رمادي',
      radiusSharp: 'حواف حادة',
      radiusDefault: 'الافتراضي',
      radiusSoft: 'حواف ناعمة',
      preview: 'معاينة',
    },
  },
  quiz: {
    modes: { practice: 'تدريب', graded: 'امتحان بدرجات' },
    practiceHint: 'محاولات غير محدودة، وهتشوف الإجابة الصح بعد كل سؤال.',
    gradedHint: 'الامتحان بدرجات — راجع إجاباتك قبل ما تسلّم.',
    start: 'ابدأ الامتحان',
    resume: 'كمّل امتحانك',
    attemptNo: 'المحاولة رقم {n}',
    attemptsLeft: 'باقي لك {n} محاولة',
    unlimitedAttempts: 'محاولات غير محدودة',
    questionCount: '{n} سؤال',
    totalMarks: 'الدرجة الكلية {marks}',
    duration: 'مدة الامتحان {minutes} دقيقة',
    noTimeLimit: 'من غير وقت محدد',
    timeLeft: 'الوقت المتبقي',
    timeAlmostUp: 'الوقت قرب يخلص',
    questionOf: 'سؤال {current} من {total}',
    next: 'التالي',
    previous: 'السابق',
    flag: 'علّم السؤال',
    unflag: 'شيل العلامة',
    flaggedCount: '{n} سؤال معلّم',
    answeredCount: 'جاوبت على {answered} من {total}',
    clearAnswer: 'امسح إجابتي',
    navigator: 'خريطة الأسئلة',
    saving: 'بيتحفظ…',
    saved: 'اتحفظ',
    saveFailed: 'مقدرناش نحفظ إجابتك — بنحاول تاني',
    staleTab: 'الامتحان ده مفتوح في مكان تاني. حدّث الصفحة عشان تكمّل من هنا.',
    submit: 'سلّم الامتحان',
    submitConfirmTitle: 'متأكد إنك عايز تسلّم؟',
    submitConfirmBody: 'بعد التسليم مش هتقدر تغيّر إجاباتك.',
    submitConfirmUnanswered: 'لسه فيه {count} سؤال من غير إجابة.',
    submitConfirmAllAnswered: 'جاوبت على كل الأسئلة.',
    submitCancel: 'ارجع للأسئلة',
    submitConfirmAction: 'أيوه، سلّم',
    alreadySubmitted: 'الامتحان ده اتسلّم خلاص.',
    timeUpTitle: 'الوقت خلص',
    timeUpBody: 'امتحانك اتسلّم تلقائيًا.',
    graceRemaining: 'الوقت خلص — عندك {seconds} ثانية تسلّم فيهم.',
    checkAnswer: 'شوف الإجابة',
    correct: 'إجابة صحيحة',
    incorrect: 'إجابة خاطئة',
    partial: 'إجابة صح جزئيًا',
    needsGrading: 'محتاج تصحيح من المدرّس',
    notAnswered: 'مجاوبتش',
    yourAnswer: 'إجابتك',
    rightAnswer: 'الإجابة الصحيحة',
    explanation: 'الشرح',
    questionFeedback: 'ملاحظة على إجابتك',
    marksEarned: '{earned} من {max}',
    resultsTitle: 'نتيجتك',
    reviewTitle: 'مراجعة إجاباتك',
    reviewLocked: 'المراجعة مش متاحة دلوقتي',
    reviewLockedUntilClose: 'هتقدر تراجع إجاباتك بعد ما الامتحان يقفل.',
    passed: 'ناجح',
    failed: 'محتاج تحاول تاني',
    passMark: 'درجة النجاح {percent}%',
    retry: 'حاول تاني',
    cooldown: 'تقدر تحاول تاني بعد {hours} ساعة',
    noAttemptsLeft: 'خلصت محاولاتك في الامتحان ده',
    closed: 'الامتحان قفل',
    notOpenYet: 'الامتحان لسه مفتحش',
    notEnrolled: 'لازم تكون مشترك في الكورس عشان تدخل الامتحان',
    previousAttempts: 'محاولاتك السابقة',
    bestScore: 'أعلى درجة',
    essayPending: 'إجابتك المقالية عند المدرّس للتصحيح',
    wordCount: '{n} كلمة',
    typeAnswer: 'اكتب إجابتك',
    chooseOne: 'اختر إجابة واحدة',
    chooseMany: 'اختر كل الإجابات الصحيحة',
    true: 'صح',
    false: 'خطأ',
    /** The join/split delimiter between multiple option bodies in a
     *  right-answer/response summary (e.g. "أ، ب") — a formatting
     *  primitive, not a message, but still Arabic-locale punctuation and so
     *  lives here rather than as a bare literal in `apps/api`/`apps/web`. */
    answerListSeparator: '، ',
    blockedTitle: 'مينفعش تدخل الامتحان دلوقتي',
    scoreBandExcellent: 'أداء ممتاز',
    scoreBandGood: 'أداء كويس',
    scoreBandNeedsWork: 'محتاج تراجع الدرس تاني',
    reviewLockedDuringBody: 'هتقدر تراجع إجاباتك بعد ما تسلّم المحاولة.',
    unansweredChipLabel: 'سؤال {n}',
  },
  appeal: {
    open: 'قدّم تظلم',
    title: 'تظلم على الدرجة',
    note: 'اكتب سبب التظلم',
    notePlaceholder: 'وضّح ليه شايف إن الدرجة محتاجة مراجعة',
    submit: 'ابعت التظلم',
    submitted: 'وصلنا تظلمك، هنراجعه ونرد عليك',
    alreadyOpen: 'عندك تظلم مفتوح على السؤال ده',
    gradeBefore: 'الدرجة قبل التظلم',
    gradeAfter: 'الدرجة بعد التظلم',
    status: { open: 'مفتوح', under_review: 'تحت المراجعة', accepted: 'اتقبل', rejected: 'اترفض' },
    resolverNote: 'رد المدرّس',
    empty: 'مفيش تظلمات دلوقتي',
    queueTitle: 'التظلمات',
    resolve: 'اعتمد القرار',
    newMark: 'الدرجة الجديدة',
    accept: 'اقبل التظلم',
    reject: 'ارفض التظلم',
    columnStudent: 'الطالب',
    columnQuiz: 'الامتحان',
    columnQuestion: 'السؤال',
    columnNote: 'السبب',
    columnAge: 'قدّم من',
    filterAll: 'الكل',
    studentResponse: 'إجابة الطالب',
    modelAnswer: 'نموذج الإجابة',
    resolveFailed: 'مقدرناش نعتمد القرار — حاول تاني',
    resolved: 'اتحل التظلم',
  },
  quizAdmin: {
    bankTitle: 'بنك الأسئلة',
    newQuestion: 'سؤال جديد',
    editQuestion: 'تعديل السؤال',
    duplicate: 'نسخة من السؤال',
    duplicateSuffix: '(نسخة)',
    category: 'التصنيف',
    stem: 'نص السؤال',
    generalFeedback: 'الشرح بعد الإجابة',
    graderInfo: 'ملاحظات للمصحح',
    type: 'نوع السؤال',
    types: {
      mcq_single: 'اختيار من متعدد — إجابة واحدة',
      mcq_multi: 'اختيار من متعدد — أكتر من إجابة',
      true_false: 'صح أو خطأ',
      short_answer: 'إجابة قصيرة',
      essay: 'سؤال مقالي',
    },
    options: 'الاختيارات',
    addOption: 'أضف اختيار',
    removeOption: 'احذف الاختيار',
    markCorrect: 'الإجابة الصحيحة',
    optionFeedback: 'تعليق على الاختيار',
    fraction: 'وزن الاختيار',
    answerPattern: 'نموذج الإجابة',
    addPattern: 'أضف نموذج إجابة',
    caseSensitive: 'يفرّق بين الحروف الكبيرة والصغيرة',
    wildcardHint: 'استخدم * بدل أي جزء من الإجابة',
    defaultMark: 'درجة السؤال',
    minWords: 'أقل عدد كلمات',
    maxWords: 'أكبر عدد كلمات',
    save: 'احفظ',
    publish: 'انشر السؤال',
    published: 'السؤال اتنشر — أي تعديل بعد كده هيعمل نسخة جديدة',
    versionBadge: 'نسخة {n}',
    draftBadge: 'مسودة',
    bulkImport: 'استيراد سريع',
    bulkImportHint: 'الصق الأسئلة، كل سؤال في فقرة، وحدد الإجابة بسطر ANSWER أو الإجابة',
    bulkImportExample:
      'سؤال ١: عاصمة مصر إيه؟\nA. القاهرة\nB. الإسكندرية\nC. أسوان\nANSWER: A\n\n' +
      'سؤال ٢: النيل بيجري من الجنوب للشمال\nTYPE: true\nA. صح\nB. خطأ\nANSWER: A',
    bulkImportPreview: 'معاينة {n} سؤال',
    bulkImportCommit: 'أضف الأسئلة للبنك',
    quizTitle: 'إعدادات الامتحان',
    slots: 'أسئلة الامتحان',
    addSlot: 'أضف سؤال من البنك',
    addPool: 'أضف مجموعة عشوائية',
    poolPickCount: 'عدد الأسئلة المسحوبة',
    reorderHint: 'اسحب السؤال عشان تغيّر ترتيبه',
    mode: 'نوع الامتحان',
    durationMinutes: 'مدة الامتحان بالدقايق',
    gradeMethod: 'طريقة احتساب الدرجة عبر المحاولات',
    gradeMethodOptions: {
      highest: 'أعلى محاولة',
      average: 'متوسط المحاولات',
      first: 'أول محاولة',
      last: 'آخر محاولة',
    },
    openFromLabel: 'يفتح من',
    openUntilLabel: 'يقفل في',
    maxAttempts: 'أقصى عدد محاولات (٠ = غير محدود)',
    retryCooldownHours: 'المدة بين المحاولات بالساعات',
    passPercent: 'نسبة النجاح',
    shuffleQuestions: 'رتّب الأسئلة عشوائيًا',
    shuffleOptions: 'رتّب الاختيارات عشوائيًا',
    navMethod: 'التنقل بين الأسئلة',
    navFree: 'حر',
    navSequential: 'بالترتيب',
    overdueHandling: 'لما الوقت يخلص',
    overdueAutosubmit: 'يتسلّم تلقائيًا',
    overdueGrace: 'مهلة إضافية للتسليم',
    overdueAbandon: 'المحاولة تتلغي',
    graceSeconds: 'مهلة التسليم بالثواني',
    reviewMatrix: 'إيه اللي الطالب يشوفه',
    windows: {
      during: 'أثناء المحاولة',
      immediatelyAfter: 'بعد التسليم مباشرة',
      laterWhileOpen: 'بعد كده والامتحان مفتوح',
      afterClose: 'بعد ما الامتحان يقفل',
    },
    flags: {
      response: 'إجابته',
      correctness: 'صح ولا غلط',
      marks: 'الدرجات',
      specificFeedback: 'تعليق كل اختيار',
      generalFeedback: 'الشرح العام',
      rightAnswer: 'الإجابة الصحيحة',
      overallFeedback: 'تعليق النتيجة',
    },
    attemptsTitle: 'محاولات الطلاب',
    unlock: 'افتح المحاولة',
    reopen: 'ارجّع المحاولة للطالب',
    grantAttempt: 'امنح محاولة إضافية',
    grantTime: 'امنح وقت إضافي',
    grantTimeMinutes: 'دقايق إضافية',
    analyticsTitle: 'تحليل الامتحان',
    scoreDistribution: 'توزيع الدرجات',
    facilityIndex: 'معامل السهولة',
    discriminationIndex: 'معامل التمييز',
    distractorAnalysis: 'تحليل الاختيارات',
    attemptCount: '{n} محاولة',
    tooFewAttempts: 'محتاجين {n} محاولة على الأقل عشان الأرقام تبقى معبّرة',
    averageScore: 'متوسط الدرجات',
    medianScore: 'الوسيط',
    passRate: 'نسبة النجاح',
    newCategory: 'فئة جديدة',
    categoryNamePlaceholder: 'اسم الفئة',
    noCategories: 'مفيش فئات لسه — أضف واحدة',
    questionsEmpty: 'مفيش أسئلة في البنك لسه',
    search: 'دور بالنص...',
    searchQuestions: 'دور على سؤال...',
    shortcutsHint: 'Ctrl/⌘+Enter للحفظ — Escape للإغلاق — Enter في آخر اختيار يضيف اختيار جديد',
    showWeights: 'وزن الاختيار (متقدم)',
    publishQuiz: 'انشر الامتحان',
    slotsEmpty: 'مفيش أسئلة في الامتحان لسه',
    slotRemove: 'احذف السؤال من الامتحان',
    poolName: 'اسم المجموعة',
    poolPoints: 'درجة كل سؤال في المجموعة',
    columnQuestion: 'السؤال',
    columnN: 'عدد المحاولات',
    distractorPicks: '{n} اختار',
    columnStudent: 'الطالب',
    columnState: 'الحالة',
    columnScore: 'الدرجة',
    columnStarted: 'وقت البدء',
    columnDeadline: 'الموعد النهائي',
    columnActions: 'إجراءات',
    stateInProgress: 'شغال',
    stateOverdue: 'اتأخر',
    stateSubmitted: 'اتسلّم',
    statePendingReview: 'محتاج تصحيح',
    stateAbandoned: 'اتلغى',
    filterAll: 'الكل',
    searchStudent: 'دور بالاسم...',
    needsGradingOnly: 'محتاج تصحيح بس',
    confirmReopen: 'متأكد إنك عايز ترجّع المحاولة دي للطالب؟',
    extraSecondsLabel: 'ثواني إضافية',
    grantAttemptConfirm: 'امنح الطالب ده محاولة إضافية؟',
    actionSucceeded: 'اتنفّذ',
    actionFailed: 'مقدرناش ننفّذ الإجراء — حاول تاني',
  },
  quizErrors: {
    exactlyOneCorrect: 'لازم تحدد إجابة صحيحة واحدة بالظبط',
    atLeastTwoOptions: 'لازم يكون فيه اختيارين على الأقل',
    trueFalseNeedsTwo: 'سؤال صح وخطأ لازم يكون له اختيارين بالظبط',
    multiWeightsMustSumToOne: 'مجموع أوزان الإجابات الصحيحة لازم يساوي 1',
    multiNeedsPositive: 'لازم يكون فيه إجابة صحيحة واحدة على الأقل',
    shortAnswerNeedsFullCredit: 'لازم يكون فيه نموذج إجابة واحد على الأقل بوزن 1',
    patternRequired: 'اكتب نموذج الإجابة',
    stemRequired: 'اكتب نص السؤال',
    optionBodyRequired: 'اكتب نص الاختيار',
    essayHasNoOptions: 'السؤال المقالي مالوش اختيارات',
    maxWordsBelowMin: 'أكبر عدد كلمات لازم يكون أكبر من أقل عدد',
    fractionRange: 'وزن الاختيار لازم يكون بين -1 و 1',
    importNoQuestions: 'مفيش أسئلة في النص ده',
    importNoAnswerLine: 'السؤال رقم {n}: مفيش سطر إجابة',
    importUnknownLetter: 'السؤال رقم {n}: حرف إجابة مش موجود ({letter})',
    importNoOptions: 'السؤال رقم {n}: مفيش اختيارات',
    importUnknownType: 'السؤال رقم {n}: نوع سؤال مش معروف',
  },
} as const;

export type Copy = typeof copy;
