/**
 * The single Arabic string table. No component may contain a user-facing literal.
 * This is what makes adding English later a routing change rather than a rewrite.
 */
export const copy = {
  site: {
    name: 'أيمن أبو العلا',
    tagline: 'البرمجة وعلوم الحاسب — نظام البكالوريا المصرية',
    instructor: 'المهندس أيمن أبو العلا',
  },
  nav: {
    home: 'الرئيسية',
    courses: 'الكورسات',
    about: 'عن المنصة',
    contact: 'تواصل معنا',
    login: 'تسجيل الدخول',
    register: 'حساب جديد',
    dashboard: 'حسابي',
  },
  theme: {
    toggle: 'تبديل المظهر',
    light: 'فاتح',
    dark: 'داكن',
    system: 'حسب النظام',
  },
  onboarding: {
    title: 'أكمل بيانات حسابك',
    subtitle: 'محتاجين شوية معلومات بسيطة عشان نظبطلك المنصة على مقاسك',
    step1Title: 'من إنت',
    step2Title: 'مكانك',
    step3Title: 'دراستك',
    optionalTitle: 'بيانات إضافية',
    optionalSubtitle: 'اختيارية دلوقتي، وهنفكرك بيها تاني بعد كده',
    fullName: 'الاسم الكامل',
    fullNamePlaceholder: 'اكتب اسمك بالكامل',
    gender: 'النوع',
    genderPlaceholder: 'اختر النوع',
    genderMale: 'ذكر',
    genderFemale: 'أنثى',
    genderError: 'اختر النوع',
    phone: 'رقم الهاتف',
    phonePlaceholder: '01012345678',
    governorate: 'المحافظة',
    governoratePlaceholder: 'اختر محافظتك',
    schoolName: 'اسم المدرسة',
    schoolNamePlaceholder: 'اختياري',
    system: 'النظام الدراسي',
    systemPlaceholder: 'اختر النظام الدراسي',
    year: 'الصف الدراسي',
    yearPlaceholder: 'اختر الصف الدراسي',
    track: 'المسار',
    trackPlaceholder: 'اختر المسار',
    electiveSubject: 'المادة الاختيارية',
    electiveSubjectPlaceholder: 'اختر المادة الاختيارية',
    fatherPhone: 'رقم هاتف الأب',
    motherPhone: 'رقم هاتف الأم',
    parentPhonePlaceholder: 'اختياري',
    skip: 'تخطي دلوقتي',
    skipHint: 'هنسألك تاني بعدين',
    undoSkip: 'إظهار الحقول',
    submit: 'حفظ ومتابعة',
    submitPending: 'جارٍ الحفظ…',
    submitError: 'تعذر حفظ بياناتك. تأكد منها وحاول تاني.',
    phoneConflictError: 'رقم الهاتف ده مسجل بحساب تاني بالفعل',
  },
  auth: {
    login: {
      title: 'تسجيل الدخول',
      subtitle: 'أهلًا بيك تاني، سجّل دخولك للمتابعة',
    },
    register: {
      title: 'إنشاء حساب جديد',
      subtitle: 'اعمل حسابك وابدأ رحلتك في البكالوريا المصرية',
    },
    fields: {
      name: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
    },
    actions: {
      login: 'تسجيل الدخول',
      loginPending: 'جارٍ تسجيل الدخول…',
      register: 'إنشاء حساب',
      registerPending: 'جارٍ إنشاء الحساب…',
    },
    switch: {
      noAccount: 'لسه معملتش حساب؟',
      createAccount: 'إنشاء حساب جديد',
      haveAccount: 'عندك حساب بالفعل؟',
      login: 'تسجيل الدخول',
    },
    providers: {
      divider: 'أو',
      google: 'المتابعة عبر جوجل',
      apple: 'المتابعة عبر أبل',
    },
    errors: {
      // One generic message per form, shown for EVERY failure reason on that
      // form (wrong password, unknown email, locked account, network error,
      // provider error). Never distinguish the cause in the UI — S1 requires
      // the login endpoint's responses to already be byte-identical across
      // failure modes, and a "helpful" UI message would quietly undo that by
      // reintroducing an enumeration signal one layer up.
      login: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      register: 'تعذر إنشاء الحساب. تأكد من البيانات وحاول تاني.',
    },
  },
  common: {
    loading: 'جارٍ التحميل',
    error: 'حصل خطأ',
    retry: 'حاول تاني',
    empty: 'مفيش حاجة هنا لسه',
    // Plan 6 append.
    undo: 'تراجع',
  },
  /**
   * Cross-cutting accessibility strings that belong to no single feature —
   * a live region's accessible NAME, not its announced content. Kept in its
   * own namespace (audit findings B5/M5) so it never collides with a
   * feature-scoped copy edit landing in the same file at the same time.
   */
  a11y: {
    toastRegionLabel: 'الإشعارات',
    skipToContent: 'تخطَّ إلى المحتوى',
    decorative: 'عنصر زخرفي',
  },
  code: {
    copy: 'انسخ الكود',
    copied: 'اتنسخ',
    label: 'مثال كود',
  },
  showpiece: {
    posterAlt: 'مجسّم ثلاثي الأبعاد بخطوط شبكية يدور ببطء',
    heading: 'الشكل اللي بنبني بيه',
  },
  settings: {
    devices: {
      title: 'أجهزتي',
      subtitle: 'الأجهزة اللي سجلت دخولك منها. تقدر تلغي أي جهاز مش عارفه.',
      current: 'الجهاز الحالي',
      loggedInAt: 'دخلت من هنا في',
      lastSeenAt: 'آخر نشاط',
      revoke: 'إلغاء الجهاز',
      revokePending: 'جارٍ الإلغاء…',
      revokeCurrentConfirm: 'ده الجهاز اللي بتستخدمه دلوقتي. لو ألغيته هتتسجل خروجك فورًا. متأكد؟',
      revokeError: 'تعذر إلغاء الجهاز. حاول تاني.',
      empty: 'مفيش أجهزة مسجلة دخول دلوقتي',
    },
  },
  home: {
    eyebrow: '01 / المنصة',
  },
  landing: {
    heroEyebrow: 'منصة أ. أيمن أبو العلا — البكالوريا المصرية',
    heroLine1: 'الكود بيتفهم،',
    heroLine2: 'مش بيتحفظ.',
    /** The hero's second line cycles through these. `heroLine2` stays as the
     *  first entry and as the static fallback under reduced motion. */
    heroRotating: ['مش بيتحفظ.', 'وبيتكتب بإيدك.', 'وبيتجرَّب بنفسك.', 'وبيتبني خطوة بخطوة.'],
    heroLead:
      'كل محاضرات البرمجة وعلوم الحاسب لطلبة البكالوريا — بشرح واضح، أمثلة حقيقية، واختبارات بتقيس فهمك مش حفظك.',
    ctaPrimary: 'ابدأ مجانًا',
    ctaSecondary: 'اتفرّج على الكورسات',
    // The signature code sample that types itself in the hero.
    codeCaption: 'محاضرة ٤ · الدوال',
    statStudents: '+١٤٠٠',
    statStudentsLabel: 'طالب فهم البرمجة',
    statHours: '+١٧',
    statHoursLabel: 'ساعة شرح وتطبيق',
    statProjects: '+٣',
    statProjectsLabel: 'مشروع عملي بإيدك',
    statRating: '٤٫٩/٥',
    statRatingLabel: 'تقييم الطلبة',
    aiEyebrow: 'نموذج حيّ',
    aiTitle: 'ورا كل «ذكاء»… بنية بسيطة',
    aiLead:
      'الشبكات العصبية اللي بتشغّل الذكاء الاصطناعي مجرد عُقد وأوزان متوصّلة ببعض — نفس المنطق اللي هتفهمه وتكتبه بإيدك في الكورس.',
    tracksEyebrow: '02 / المنهج',
    tracksTitle: 'مبني على المنهج، مش بعيد عنه',
    tracksLead:
      'كل درس متربوط بمساره وصفّه في نظام البكالوريا — تذاكر اللي هييجي في الامتحان بالظبط، من غير لف ولا دوران.',
    featuresEyebrow: '03 / ليه هنا',
    featuresTitle: 'اتعلّمت عشان تفهم',
    feature1Title: 'شرح خطوة بخطوة',
    feature1Body: 'كل فكرة متبنية على اللي قبلها، بأمثلة من كود حقيقي تكتبه بإيدك.',
    feature2Title: 'اختبارات بتصحّح لحظيًا',
    feature2Body: 'تعرف غلطك في وقته، مع مراجعة توضّح إجابتك صح ولا غلط وليه.',
    feature3Title: 'متابعة تقدّمك',
    feature3Body: 'كل درس بتخلّصه بيتسجّل، فتعرف إنت واصل فين ومحتاج ترجع لفين.',
    instructorEyebrow: '04 / المُحاضر',
    instructorTitle: 'مين اللي بيشرحلك',
    instructorName: 'أ. أيمن أبو العلا',
    instructorBody:
      'مدرّس البرمجة وعلوم الحاسب لطلبة البكالوريا المصرية — بأسلوب بيبسّط الصعب ويخلّيك تكتب كود من أول محاضرة.',
    finalTitle: 'جاهز تبدأ؟',
    finalLead: 'اعمل حسابك في دقيقة وابدأ أول محاضرة — مجانًا.',
    finalCta: 'اعمل حساب',

    // tracks (code-editor cards, one per track)
    tracksSelectEyebrow: 'اختر مسارك',
    tracksSelectTitle: 'اختر مستواك.. وابدأ أول Commit',
    tracksSelectLead: 'سواء بتبدأ من الصفر أو بتذاكر منهجك، فيه مسار جاهز ليك.',
    trackEssentialsTag: 'تمهيد · ESSENTIALS',
    trackEssentialsTitle: 'مفاهيم تأسيسية',
    trackEssentialsBody: 'تسخين سريع: أهم المصطلحات والأفكار اللي هتقابلك في أي لغة برمجة.',
    trackEssentialsCta: 'ابدأ التمهيد',
    trackYear1Tag: 'المسار · 01',
    trackYear1Title: 'الصف الأول',
    trackYear1Body: 'كل كورسات أولى: شرح المنهج، تمارين عملية، ومراجعات الامتحانات.',
    trackYear1Cta: 'اختر الصف',
    trackYear2Tag: 'المسار · 02 — نشط',
    trackYear2Title: 'الصف الثاني',
    trackYear2Body: 'كل كورسات تانية: شرح المنهج، تمارين عملية، ومراجعات الامتحانات.',
    trackYear2Cta: 'افتح كورسات الصف',

    // courses teaser
    coursesEyebrow: 'كورساتنا',
    coursesTitle: 'اختار الكورس وابدأ على طول',
    coursesLead: 'كل كورس فيه شرح، تمارين عملية، ومتابعة مستمرة — مرتّب بالصف والمسار.',
    coursesCta: 'كل الكورسات',
    courseFree: 'كورس مجاني',
    courseOpen: 'الدخول للكورس',

    // FAQ
    faqEyebrow: 'الأسئلة الشائعة',
    faqTitle: 'أسئلة بتتسأل كتير',
    faq1Q: 'أقدر أبدأ من غير أي خلفية في البرمجة؟',
    faq1A: 'أيوه — فيه مسار تأسيسي بيبدأ معاك من الصفر: الأساسيات الأول، وبعدين كود بتمارين عملية خطوة بخطوة.',
    faq2Q: 'هكتب كود فعلًا ولا مجرد مشاهدة؟',
    faq2A: 'هتكتب وتجرّب بإيدك من أول حصة — كل جزئية عليها تدريب حقيقي يثبّت اللي اتعلمته.',
    faq3Q: 'فيه متابعة واختبارات؟',
    faq3A: 'أيوه — متابعة أولًا بأول واختبارات دورية بتصحّح لحظيًا وتعرّفك واقف فين.',
    faq4Q: 'المنصة مناسبة لمين؟',
    faq4A: 'لطلبة البكالوريا اللي بيدرسوا البرمجة وعلوم الحاسب — من أول مبتدئ لحد اللي عايز يتقن ويجهّز للامتحان.',
    faq5Q: 'لو قابلتني مشكلة في حسابي أعمل إيه؟',
    faq5A: 'كلّمنا في أي وقت وهنساعدك — فيه دعم مستمر للطلبة.',

    // interactive playground
    playEyebrow: 'مختبر تفاعلي',
    playTitle: 'اكتب الكود وشوف النتيجة فورًا',
    playLead: 'جرّب وعدّل وشغّل بنفسك — النتيجة والأخطاء هتظهر قدامك في الحال، عشان تتعلّم بالممارسة مش بالحفظ.',
    playRun: 'شغّل الكود',
    playRunning: 'بيشتغل…',
    playReset: 'إعادة المثال',
    playConsole: 'Console — النتيجة',
    playEmpty: 'اكتب الكود واضغط «شغّل الكود» — النتيجة هتظهر هنا.',
    playTimeout: 'الكود خد وقت طويل — يمكن فيه حلقة لا نهائية؟',

    // footer
    footerTagline: 'منصة أ. أيمن أبو العلا — للبرمجة وعلوم الحاسب',
    footerRights: 'جميع الحقوق محفوظة © 2026',
    footerPages: 'الصفحات',
    footerHome: 'الرئيسية',
    footerRegister: 'إنشاء حساب',
    footerLogin: 'تسجيل الدخول',
    footerFollow: 'تابعنا',
    footerContact: 'تواصل معنا',
    footerCommunity: 'مجتمع الطلاب',
    footerYoutube: 'يوتيوب',
    footerTiktok: 'تيك توك',
    footerFacebook: 'فيسبوك',
    footerWhatsappChannel: 'قناة واتساب',
    footerFacebookGroup: 'جروب فيسبوك',
    footerWhatsapp: 'تواصل معنا عبر واتساب',

    // ---- "why learn here" — the two-column vertical marquee ----
    whyTitle: 'ليه تتعلم البرمجة مع',
    whyTitleAccent: 'المهندس أيمن؟',
    whyLead: 'الطريقة هنا مبنية على إنك تفهم وتجرّب بنفسك، مش تتفرج وتحفظ.',
    whyLeadSecondary:
      'وكل ده من مكان واحد: دروسك وتمارينك ومتابعتك ونتايجك، خطوة ورا خطوة لحد المشروع الكامل.',
    whyListLabel: 'مميزات التعلم على المنصة',
    why1Title: 'بداية من الصفر',
    why1Body: 'مش محتاج أي خلفية سابقة، بنبدأ معاك من أول خطوة.',
    why2Title: 'كود من أول حصة',
    why2Body: 'هتكتب وتجرّب بنفسك من أول درس، مش مجرد مشاهدة.',
    why3Title: 'تمارين عملية',
    why3Body: 'كل جزئية عليها تدريب حقيقي يثبّت اللي اتعلمته.',
    why4Title: 'متابعة مستمرة',
    why4Body: 'متابعة أولًا بأول واختبارات دورية تعرّفك واقف فين.',
    why5Title: 'مشروع كامل',
    why5Body: 'بتوصل في الآخر لمشروع شغّال بنيته بإيدك خطوة بخطوة.',
    why6Title: 'تجهيز للامتحانات',
    why6Body: 'مراجعات منظمة لامتحانات الشهور والامتحانات النهائية.',
    why7Title: 'مرتبط بالمنهج',
    why7Body: 'كل درس متربوط بصفّه ومساره في نظام البكالوريا المصرية.',
    why8Title: 'فهم مش حفظ',
    why8Body: 'تفهم الفكرة ومنين جت الأول، وبعدين تكتبها كود.',

    // ---- tracks / choose your year ----
    tracksSelectBadge: 'SELECT YOUR TRACK',

    // ---- interactive code lab ----
    playFile: 'playground.js',
    playLang: 'JS',
    playEditorLabel: 'editor',
    playExampleLabel: 'اختر مثال',
    playHint: '⌘ / Ctrl + Enter',
    playClear: 'امسح النتيجة',
    playCopy: 'انسخ الكود',
    playCopied: 'اتنسخ ✓',
    playConsoleIdle: 'جاهز',
    playConsoleLines: 'سطر',
    playConsoleErrors: 'خطأ',
    playConsoleClear: 'امسح',
    playExampleStart: 'البداية',
    playExampleVars: 'المتغيرات',
    playExampleConditions: 'الشروط',
    playExampleLoops: 'الحلقات',
    playExampleFunctions: 'الدوال',
    playExampleArrays: 'المصفوفات',
    playExampleErrors: 'الأخطاء',
    playEditorAria: 'محرّر الكود',
    playWorkerError: 'حصل خطأ أثناء التشغيل',
    playUnavailable: 'مش قادرين نشغّل الكود دلوقتي',
    playNoOutput: 'تمام — الكود اشتغل من غير أي ناتج.',

    // ---- the instructor's profile card ----
    profileTier: 'المنصة الرسمية',
    profileRole: 'مدرس البرمجة وعلوم الحاسب — البكالوريا المصرية',
    profileCoursesLabel: 'كورس',
    profileStudentsLabel: 'طالب',
    profileHoursLabel: 'ساعة شرح',
    profileCta: 'كل الكورسات',
    profileSecondary: 'عن المهندس',
    profileAll: 'الكل',
    profileYear: 'الصف',
    profileEmpty: 'مفيش كورسات في الصف ده لسه.',

    // ---- about the instructor ----
    aboutTitle: 'مين المهندس أيمن أبو العلا؟',
    aboutBody1:
      'مهندس متخصص في تدريس البرمجة وعلوم الحاسب لطلبة البكالوريا المصرية — أونلاين ومن السنتر.',
    aboutBody2:
      'طريقته قايمة على الفهم قبل الحفظ: بتكتب كود من أول حصة، وتتدرب بتمارين ومشاريع حقيقية، ومعاها متابعة واختبارات مستمرة لحد ما تبني مشروعك الكامل.',
    aboutRole: 'مدرس البرمجة وعلوم الحاسب للمرحلة الثانوية',
    aboutChip1: 'شرح عملي',
    aboutChip2: 'تدريب مستمر',
    aboutChip3: 'متابعة واختبارات',

    // ---- extra FAQ rows ----
    faq6Q: 'إزاي بذاكر على المنصة؟',
    faq6A: 'تختار كورس صفّك، وتمشي في الدروس بالترتيب: فيديو، وبعده تمرين، وبعده اختبار قصير يقيس فهمك.',
    faq7Q: 'هتعلم إيه بالظبط؟',
    faq7A: 'أساسيات البرمجة الأول — متغيرات ودوال وشروط وحلقات ومصفوفات — وبعدين تطبيق عملي على منهج صفّك لحد المشروع الكامل.',
  },
  years: {
    title: 'كورسات',
    year1: 'الصف الأول بكالوريا',
    year2: 'الصف الثاني بكالوريا',
    year3: 'الصف الثالث بكالوريا',
    filterAll: 'كل التصنيفات',
    filterFree: 'الكورسات المجانية',
    empty: 'مفيش كورسات منشورة للصف ده لسه.',
  },
  essentials: {
    badge: 'WARM-UP',
    title: 'قبل ما تكتب أول سطر كود',
    leadBefore: 'اتعرّف على أهم المصطلحات اللي هتقابلك في أي لغة برمجة، بشرح بسيط وسريع يساعدك تبدأ وإنت',
    leadCode: 'ready = true',
    leadAfter: 'فاهم.',
    cta: 'اختار صفّك',
    listTitle: '١٢ مفهوم هتحتاجهم من أول يوم',
    listLead: 'مصطلحات واضحة بالعربي والإنجليزي — من غير لف، ومن غير ادّعاءات.',
    t1Ar: 'متغيّر',
    t1Body: 'حاوية بنخزّن فيها قيمة، ونقدر نقراها أو نغيّرها بعدين.',
    t2Ar: 'دالة',
    t2Body: 'مجموعة أوامر تحت اسم واحد، بننفّذها كل ما نحتاج.',
    t3Ar: 'حلقة',
    t3Body: 'تكرار تنفيذ كود معيّن أكتر من مرّة بشرط محدّد.',
    t4Ar: 'مصفوفة',
    t4Body: 'قائمة بتخزّن أكتر من قيمة ورا بعض بترتيب وفهرسة.',
    t5Ar: 'شرط',
    t5Body: 'قرار: لو الكلام ده صح اعمل كذا، وغير كده اعمل حاجة تانية.',
    t6Ar: 'كائن',
    t6Body: 'حاجة ليها خصائص وسلوك، بنجمّع بياناتها في مكان واحد.',
    t7Ar: 'نوع البيانات',
    t7Body: 'نوع القيمة: رقم، نص، منطقي (صح/غلط)، أو غيرهم.',
    t8Ar: 'مُعامل',
    t8Body: 'رمز بيشتغل على القيم: جمع، طرح، مقارنة، أو منطق.',
    t9Ar: 'خطأ',
    t9Body: 'رسالة بتقولك إيه اللي غلط وفين — مش عقاب، ده دليل.',
    t10Ar: 'تعليق',
    t10Body: 'كلام للبني آدمين مش للكمبيوتر، بيشرح الكود لنفسك ولغيرك.',
    t11Ar: 'مُدخل ومُخرج',
    t11Body: 'الكود بياخد بيانات من برّه، وبيطلّع نتيجة تشوفها.',
    t12Ar: 'خوارزمية',
    t12Body: 'خطوات مرتّبة بتوصّل لحل مسألة — الفكرة قبل ما تبقى كود.',
  },
  catalog: {
    eyebrow: '03 / الكورسات',
    title: 'الكورسات',
    subtitle: 'كل محاضرات البرمجة وعلوم الحاسب، مرتبة بالصف والمسار',
    empty: 'مفيش كورسات منشورة لسه',
    lessonCount: 'محاضرة',
    duration: 'المدة',
    minutes: 'دقيقة',
    hours: 'ساعة',
    freePreview: 'معاينة مجانية',
    free: 'مجاني',
    open: 'افتح الكورس',
  },
  course: {
    back: 'العودة',
    lessons: 'الدروس',
    freeBanner: 'الكورس ده مجاني !',
    lessonsLabel: 'الدروس:',
    watch: 'مشاهدة',
    takeQuiz: 'امتحن',
    breadcrumbHome: 'الرئيسية',
    breadcrumbCatalog: 'الكورسات',
    content: 'محتوى الكورس',
    about: 'عن الكورس',
    instructor: 'المُحاضر',
    start: 'ابدأ الكورس',
    continue: 'كمّل الكورس',
    enrolled: 'إنت مشترك في الكورس ده',
    notFound: 'الكورس ده مش موجود',
    lessonKind: {
      video: 'فيديو',
      quiz: 'اختبار',
      attachment: 'مرفق',
      text: 'قراءة',
    },
  },
  player: {
    eyebrow: '09 / المشغّل',
    outline: 'محتوى الكورس',
    previous: 'الدرس السابق',
    next: 'الدرس التالي',
    markComplete: 'أنهيت الدرس · التالي',
    markCompleteFinal: 'أنهيت الدرس',
    marking: 'بنسجّل…',
    completed: 'تم',
    inProgress: 'جارٍ',
    notStarted: 'لسه',
    play: 'شغّل الفيديو',
    videoUnavailable: 'الفيديو مش متاح دلوقتي',
    attachments: 'الملفات المرفقة',
    download: 'تحميل',
    quizIntro: 'الدرس ده اختبار. ابدأ لما تكون جاهز.',
    quizCta: 'ابدأ الاختبار',
    courseProgress: 'تقدّمك في الكورس',
    lessonsCompleted: 'درس مكتمل من',
    autoCompleteHint: 'الدرس بيتحسب لوحده لما توصل لآخر الفيديو وتكون شُفت معظمه.',
    manualOnlyHint: 'مدة الفيديو مش متسجّلة، فاضغط «أنهيت الدرس» لما تخلّص.',
    saveFailed: 'مش قادرين نسجّل تقدّمك دلوقتي',
  },
  dashboard: {
    eyebrow: '01 / حسابي',
    title: 'حسابي',
    continueWatching: 'أكمل من حيث وقفت',
    continueCta: 'كمّل',
    remaining: 'باقي',
    myCourses: 'كورساتي',
    recentScores: 'آخر النتائج',
    noScoresYet: 'لسه مفيش نتائج. أول اختبار تخلّصه هيظهر هنا.',
    noCoursesYet: 'لسه مش مشترك في أي كورس.',
    browseCourses: 'اتفرّج على الكورسات',
  },
  enrollment: {
    enroll: 'اشترك في الكورس',
    enrolled: 'أنت مشترك',
    enrolling: 'بنشتركك…',
    startCourse: 'ابدأ الكورس',
  },
  admin: {
    nav: {
      dashboard: 'لوحة التحكم',
      content: 'المحتوى',
      courses: 'الكورسات',
      questions: 'بنك الأسئلة',
      appeals: 'التظلمات',
      // ── Plan 6 appends below. Plan 3 owns this sub-namespace; entries are
      // ADDED here, never rewritten, or every existing admin link breaks.
      overview: 'نظرة عامة',
      students: 'الطلبة',
      attempts: 'المحاولات',
      taxonomy: 'الهيكل الدراسي',
      home: 'الصفحة الرئيسية',
      navigation: 'القوائم',
      branding: 'الهوية البصرية',
      flags: 'خصائص التشغيل',
      media: 'مكتبة الوسائط',
      audit: 'سجل النشاط',
      settings: 'الإعدادات',
    },
    common: {
      create: 'إضافة',
      save: 'حفظ',
      saving: 'جارٍ الحفظ',
      saved: 'اتحفظ',
      saveFailed: 'الحفظ فشل — التغييرات اترجعت زي ما كانت',
      cancel: 'إلغاء',
      close: 'إغلاق',
      delete: 'حذف',
      deleteConfirm: 'متأكد؟ الإجراء ده مش هيترجع.',
      required: 'الحقل ده مطلوب',
      publish: 'نشر',
    },
    course: {
      listTitle: 'الكورسات',
      new: 'كورس جديد',
      title: 'اسم الكورس',
      edit: 'تعديل الكورس',
      slug: 'المُعرّف في الرابط',
      slugHint: 'حروف إنجليزي صغيرة وأرقام وشرطات — ده اللي بيظهر في العنوان',
      subtitle: 'وصف مختصر',
      description: 'الوصف',
      system: 'النظام الدراسي',
      year: 'الصف الدراسي',
      track: 'المسار',
      trackNoneYear1: 'الصف الأول مالوش مسار',
      subject: 'المادة',
      subjectEmpty: 'مفيش مواد متاحة للاختيار ده — جرّب نظام أو صف أو مسار تاني',
      status: 'الحالة',
      statusDraft: 'مسودة',
      statusPublished: 'منشور',
      statusArchived: 'مؤرشف',
      publish: 'نشر',
      unpublish: 'رجّعه مسودة',
      publishBlocked: 'لازم يكون فيه محاضرة منشورة واحدة على الأقل',
      // I4 (audit): a course with student quiz attempts can never be
      // hard-deleted — attempt_events is append-only at the database level,
      // by design, forever. Archiving (not unpublishing back to draft) is
      // the correct action: it is a distinct, permanent retirement state,
      // not "still being worked on".
      deleteBlockedAttempts: 'الكورس ده فيه محاولات امتحانات لطلبة، فمينفعش يتمسح خالص — أرشفه بدل ما تمسحه',
      archiveConfirm: 'متأكد إنك عايز تؤرشف الكورس ده؟ هيتشال من واجهة الطلبة.',
      restoreConfirm: 'متأكد إنك عايز ترجّع الكورس ده مسودة؟',
      deleteConfirm: 'متأكد إنك عايز تمسح الكورس ده؟ الإجراء ده مش هيترجع.',
      empty: 'مفيش كورسات لسه',
    },
    section: {
      new: 'قسم جديد',
      title: 'اسم القسم',
      summary: 'نبذة',
      empty: 'مفيش أقسام لسه',
    },
    lesson: {
      new: 'محاضرة جديدة',
      title: 'عنوان المحاضرة',
      kind: 'النوع',
      freePreview: 'معاينة مجانية',
      estimatedSeconds: 'المدة التقديرية بالثواني',
      videoUrl: 'رابط يوتيوب',
      videoUrlHint: 'بناخد كود الفيديو (11 حرف) بس — الباقي بيتشال ومحدش بيفتح الرابط',
      videoUrlInvalid: 'الرابط ده مش رابط يوتيوب صالح',
      durationSeconds: 'مدة الفيديو بالثواني',
      body: 'محتوى الدرس',
      empty: 'مفيش محاضرات في القسم ده',
    },
    reorder: {
      hint: 'اسحب لإعادة الترتيب، أو استخدم زر المسافة والأسهم من الكيبورد',
      handle: 'مقبض السحب',
      pickedUp: 'اتمسكت المحاضرة في الترتيب رقم',
      movedOver: 'بقت في الترتيب رقم',
      dropped: 'اتسابت في الترتيب رقم',
      cancelled: 'اتلغى السحب والترتيب رجع زي ما كان',
    },
    // ── Plan 6 owns everything from here down inside `admin` ───────────────
    title: 'لوحة التحكم',
    signedInAs: 'داخل باسم',
    openMenu: 'فتح القائمة',
    overviewLead: 'كل حاجة في الموقع بتتظبط من هنا.',
    // ── Task 16 appends more keys under commandPalette (search, groups, empty).
    commandPalette: {
      trigger: 'البحث السريع',
    },
    shortcuts: {
      paletteLabel: 'لوحة الأوامر',
      placeholder: 'دور على أمر أو صفحة...',
      navigate: 'التنقل',
      act: 'إجراءات',
      newNavItem: 'عنصر قائمة جديد',
      upload: 'ارفع صورة',
    },
    actions: {
      save: 'حفظ',
      saving: 'جارٍ الحفظ',
      saved: 'تم الحفظ',
      cancel: 'إلغاء',
      undo: 'تراجع',
      delete: 'حذف',
      archive: 'أرشفة',
      restore: 'استرجاع',
      publish: 'نشر',
      unpublish: 'إلغاء النشر',
      create: 'إضافة',
      edit: 'تعديل',
      confirm: 'تأكيد',
      undone: 'اترجع',
    },
    settings: {
      title: 'إعدادات المنصة',
      sectionBranding: 'الهوية البصرية',
      sectionSeo: 'بيانات محركات البحث',
      sectionContact: 'وسائل التواصل',
      accent: 'اللون الأساسي',
      radius: 'حدة الحواف',
      logoLight: 'الشعار — الوضع الفاتح',
      logoDark: 'الشعار — الوضع الداكن',
      favicon: 'أيقونة الموقع',
      seoTitle: 'عنوان الموقع',
      seoDescription: 'وصف الموقع',
      email: 'البريد الإلكتروني',
      phone: 'رقم الهاتف',
      whatsapp: 'واتساب',
      facebook: 'فيسبوك',
      youtube: 'يوتيوب',
      telegram: 'تليجرام',
      // ── Task 8 (settings editor form) appends below.
      logoLightHint: 'بيظهر في الوضع الفاتح',
      logoDarkHint: 'بيظهر في الوضع الداكن',
      ogImage: 'صورة المشاركة',
      assetNone: 'بدون',
      seoTitleHint: 'حتى 70 حرف — بيظهر في تبويب المتصفح ونتائج البحث',
      seoDescriptionHint: 'حتى 160 حرف — الوصف اللي بيظهر تحت العنوان في نتائج البحث',
      phoneHint: 'بصيغة دولية، يعني +20 وبعدها الرقم',
      urlHttpsOnly: 'لازم يبدأ بـ https://',
      accentPreviewLabel: 'معاينة اللون',
    },
    branding: {
      title: 'الهوية البصرية',
      lead: 'الألوان بتتختار من مجموعة جاهزة — مفيش كتابة ألوان بإيدك.',
      accentAmber: 'كهرماني',
      accentCyan: 'سماوي',
      accentBlue: 'أزرق',
      accentViolet: 'بنفسجي',
      accentMagenta: 'أرجواني',
      accentSlate: 'رمادي',
      radiusSharp: 'حواف حادة',
      radiusDefault: 'الافتراضي',
      radiusSoft: 'حواف ناعمة',
      preview: 'معاينة',
    },
    list: {
      searchPlaceholder: 'دور...',
      clearFilters: 'امسح الفلاتر',
      selectedCount: '{n} متحدد',
      page: 'صفحة',
      of: 'من',
      perPage: 'عدد الصفوف',
      first: 'الأولى',
      previous: 'السابقة',
      next: 'التالية',
      last: 'الأخيرة',
      noResults: 'مفيش نتائج مطابقة',
      selectAll: 'حدد الكل',
      selectRow: 'حدد الصف',
    },
    students: {
      columnName: 'الاسم',
      columnEmail: 'البريد الإلكتروني',
      columnPhone: 'رقم الهاتف',
      columnGovernorate: 'المحافظة',
      columnYear: 'الصف',
      columnTrack: 'المسار',
      columnOnboarding: 'حالة التسجيل',
      columnCreatedAt: 'تاريخ الانضمام',
      onboardingDone: 'اكتمل التسجيل',
      onboardingPending: 'لسه ما كملش',
      filterGovernorate: 'المحافظة',
      filterYear: 'الصف',
      filterTrack: 'المسار',
      detailTitle: 'بيانات الطالب',
      backToList: 'رجوع لقائمة الطلبة',
      profileSection: 'البيانات الشخصية',
      academicSection: 'البيانات الدراسية',
      fullName: 'الاسم بالكامل',
      schoolName: 'اسم المدرسة',
      fatherPhone: 'رقم هاتف ولي الأمر',
      motherPhone: 'رقم هاتف الأم',
      electiveSubject: 'المادة الاختيارية',
      memberSince: 'عضو من',
      currentRole: 'الدور الحالي',
      roleAdmin: 'مسؤول',
      roleStudent: 'طالب',
      changeRole: 'تغيير الدور',
      roleChangeTitle: 'تغيير دور المستخدم',
      roleChangeNewRole: 'الدور الجديد',
      roleChangeReason: 'سبب التغيير',
      roleChangeReasonPlaceholder: 'وضّح سبب تغيير الدور — هيتسجل في سجل النشاط',
      roleChangeConfirm: 'تأكيد التغيير',
      roleChangeSuccess: 'اتغيّر الدور',
      roleChangeFailed: 'مقدرناش نغيّر الدور — حاول تاني',
      roleChangeSelfError: 'مينفعش تغيّر دورك إنت',
      roleChangeLastAdminError: 'ده آخر مسؤول في المنصة — مينفعش تلغي صلاحياته',
      saveSuccess: 'اتحفظت بيانات الطالب',
      saveFailed: 'مقدرناش نحفظ — حاول تاني',
    },
    taxonomy: {
      title: 'الهيكل الدراسي',
      lead: 'الأنظمة الدراسية والمحافظات والمسارات والمواد — بما فيها الأسماء بالعربي.',
      governoratesTitle: 'المحافظات',
      systemsTitle: 'الأنظمة الدراسية',
      tracksTitle: 'المسارات',
      subjectsTitle: 'المواد',
      columnName: 'الاسم',
      columnSlug: 'المُعرّف',
      columnRegion: 'المنطقة',
      columnActive: 'مفعّلة',
      active: 'مفعّلة',
      inactive: 'غير مفعّلة',
      columnSortOrder: 'الترتيب',
      columnTotalMarks: 'الدرجة الكلية',
      columnPassPercent: 'نسبة النجاح %',
      columnAllowsRetakes: 'بيسمح بإعادة السنة',
      columnSystem: 'النظام',
      columnMinYear: 'أقل صف',
      columnAliases: 'أسماء بديلة',
      regionUrban: 'حضر',
      regionLower: 'وجه بحري',
      regionUpper: 'وجه قبلي',
      regionFrontier: 'حدودي',
      edit: 'تعديل',
      newTrack: 'مسار جديد',
      newSubject: 'مادة جديدة',
      slugHint: 'حروف إنجليزي صغيرة وأرقام وشرطات — ثابت بعد الإنشاء',
      slugImmutable: 'المُعرّف ثابت ومينفعش يتغيّر بعد الإنشاء',
      deleteConfirm: 'متأكد إنك عايز تحذف المادة دي؟',
      subjectInUse: 'المادة مرتبطة بمقرر دراسي — احذف المقرر الأول',
      saveSuccess: 'اتحفظ',
      saveFailed: 'مقدرناش نحفظ — حاول تاني',
      academicYearsTitle: 'الصفوف الدراسية',
    },
    media: {
      title: 'مكتبة الوسائط',
      lead: 'الصور بتتحول لـ WebP تلقائيًا وبتتحفظ باسم عشوائي — الاسم الأصلي والبيانات المخفية بتتشال.',
      upload: 'ارفع صورة',
      uploading: 'جارٍ الرفع…',
      uploadSuccess: 'اترفعت الصورة',
      uploadFailed: 'مقدرناش نرفع الصورة — تأكد إنها PNG أو JPEG أو WebP أو AVIF أو GIF وأصغر من 8 ميجا',
      dropHint: 'اسحب صورة هنا أو دوس عشان تختار ملف',
      altLabel: 'وصف الصورة',
      altPlaceholder: 'وصف مختصر للصورة',
      archive: 'أرشفة',
      restore: 'استرجاع',
      archived: 'مؤرشفة',
      showArchived: 'اعرض المؤرشف',
      empty: 'مفيش صور لسه',
      dimensions: '{width}×{height}',
      sizeKb: '{kb} ك.ب',
    },
    flags: {
      title: 'خصائص التشغيل',
      lead: 'تشغيل أو إيقاف خصائص المنصة من غير أي نشر جديد للكود.',
      toggleSuccess: 'اتحفظت الخاصية',
      toggleFailed: 'مقدرناش نغيّر الخاصية — حاول تاني',
    },
    navigation: {
      title: 'القوائم',
      lead: 'عناصر القائمة — اسحب لإعادة الترتيب على مستويين.',
      newItem: 'عنصر جديد',
      newChild: 'عنصر فرعي',
      editItem: 'تعديل العنصر',
      label: 'النص الظاهر',
      href: 'الرابط',
      hrefHint: 'رابط داخلي بيبدأ بـ / زي /courses',
      icon: 'الأيقونة (اختياري)',
      parent: 'العنصر الأب',
      noParent: 'بدون — مستوى أول',
      visibleTo: 'يظهر لمين',
      visibleToHint: 'من غير أي صلاحية محددة، العنصر يظهر للجميع',
      published: 'منشور',
      archiveConfirm: 'متأكد إنك عايز تؤرشف العنصر ده؟',
      archived: 'اتأرشف العنصر',
      archiveUndo: 'تراجع',
      restored: 'اترجع العنصر',
      saveFailed: 'مقدرناش نحفظ — حاول تاني',
      saveSuccess: 'اتحفظ',
      emptyChildren: 'مفيش عناصر فرعية',
    },
    home: {
      title: 'الصفحة الرئيسية',
      lead: 'ترتيب أقسام الصفحة الرئيسية — اسحب لإعادة الترتيب.',
      addBlock: 'أضف قسم',
      preview: 'معاينة',
      published: 'منشور',
      unpublished: 'مسودة',
      publish: 'انشر',
      unpublish: 'إلغاء النشر',
      archiveConfirm: 'متأكد إنك عايز تؤرشف القسم ده؟',
      archived: 'اتأرشف القسم',
      restored: 'اترجع القسم',
      saveSuccess: 'اتحفظ',
      saveFailed: 'مقدرناش نحفظ — حاول تاني',
      blockTypeHero: 'قسم البداية',
      blockTypeCourseGrid: 'شبكة كورسات',
      blockTypeStats: 'إحصائيات',
      blockTypeTestimonials: 'آراء الطلبة',
      blockTypeFaq: 'أسئلة شائعة',
      blockTypeCta: 'دعوة لإجراء',
      keyLabel: 'مُعرّف القسم',
      keyHint: 'حروف إنجليزي صغيرة وأرقام وشرطات — ثابت بعد الإنشاء',
      headline: 'العنوان الرئيسي',
      subheadline: 'العنوان الفرعي',
      ctaLabel: 'نص الزرار',
      ctaHref: 'رابط الزرار',
      blockTitle: 'عنوان القسم',
      statLabel: 'التسمية',
      statValue: 'القيمة',
      addStat: 'أضف إحصائية',
      testimonialName: 'الاسم',
      testimonialBody: 'الرأي',
      addTestimonial: 'أضف رأي',
      faqQuestion: 'السؤال',
      faqAnswer: 'الإجابة',
      addFaq: 'أضف سؤال',
      removeItem: 'احذف',
      courseLimit: 'أقصى عدد كورسات معروضة',
    },
    audit: {
      title: 'سجل النشاط',
      lead: 'كل تغيير في لوحة التحكم بيتسجل هنا، ومتسلسل بحيث أي تعديل عليه بعد كده بيتكشف.',
      chainOk: 'سلسلة السجل سليمة',
      chainOkCount: '{n} صف',
      chainBroken: 'سلسلة السجل اتكسرت',
      chainBrokenAt: 'أول صف مكسور: {id}',
      verifyButton: 'تحقق من السلسلة',
      verifying: 'جارٍ التحقق…',
      verifyHint: 'السجل كبير — دوس على الزرار عشان تتحقق من السلسلة',
      columnTime: 'الوقت',
      columnActor: 'المستخدم',
      columnAction: 'الإجراء',
      columnResource: 'العنصر',
      columnOutcome: 'النتيجة',
      columnMetadata: 'تفاصيل',
      columnHash: 'البصمة',
      outcomeSuccess: 'نجح',
      outcomeFailure: 'فشل',
      outcomeDenied: 'اتمنع',
      noActor: 'النظام',
      filterAction: 'الإجراء',
      filterResourceType: 'نوع العنصر',
      filterActor: 'المستخدم',
      filterOutcome: 'النتيجة',
      filterAll: 'الكل',
      viewMetadata: 'اعرض التفاصيل',
    },
  },
  quiz: {
    modes: { practice: 'تدريب', graded: 'امتحان بدرجات' },
    practiceHint: 'محاولات غير محدودة، وهتشوف الإجابة الصح بعد كل سؤال.',
    gradedHint: 'الامتحان بدرجات — راجع إجاباتك قبل ما تسلّم.',
    start: 'ابدأ الامتحان',
    resume: 'كمّل امتحانك',
    attemptNo: 'المحاولة رقم {n}',
    attemptsLeft: 'باقي لك {n} محاولة',
    unlimitedAttempts: 'محاولات غير محدودة',
    questionCount: '{n} سؤال',
    totalMarks: 'الدرجة الكلية {marks}',
    duration: 'مدة الامتحان {minutes} دقيقة',
    noTimeLimit: 'من غير وقت محدد',
    timeLeft: 'الوقت المتبقي',
    timeAlmostUp: 'الوقت قرب يخلص',
    /** Discrete screen-reader announcements at meaningful countdown
     *  thresholds only (`aria-live="polite"`, `quiz-timer.tsx`) — the visual
     *  clock still ticks every second, but a per-second `aria-live` update
     *  would interrupt a screen-reader user constantly during an exam
     *  (I7). Fixed strings, not a template over a raw number, because these
     *  fire at four known instants only. */
    timeRemaining10Min: 'باقي 10 دقايق على انتهاء وقت الامتحان',
    timeRemaining5Min: 'باقي 5 دقايق على انتهاء وقت الامتحان',
    timeRemaining1Min: 'باقي دقيقة واحدة على انتهاء وقت الامتحان',
    timeRemaining30Sec: 'باقي 30 ثانية على انتهاء وقت الامتحان',
    questionOf: 'سؤال {current} من {total}',
    next: 'التالي',
    previous: 'السابق',
    flag: 'علّم السؤال',
    unflag: 'شيل العلامة',
    flaggedCount: '{n} سؤال معلّم',
    answeredCount: 'جاوبت على {answered} من {total}',
    clearAnswer: 'امسح إجابتي',
    navigator: 'خريطة الأسئلة',
    saving: 'بيتحفظ…',
    saved: 'اتحفظ',
    saveFailed: 'مقدرناش نحفظ إجابتك — بنحاول تاني',
    staleTab: 'الامتحان ده مفتوح في مكان تاني. حدّث الصفحة عشان تكمّل من هنا.',
    submit: 'سلّم الامتحان',
    submitConfirmTitle: 'متأكد إنك عايز تسلّم؟',
    submitConfirmBody: 'بعد التسليم مش هتقدر تغيّر إجاباتك.',
    submitConfirmUnanswered: 'لسه فيه {count} سؤال من غير إجابة.',
    submitConfirmAllAnswered: 'جاوبت على كل الأسئلة.',
    submitCancel: 'ارجع للأسئلة',
    submitConfirmAction: 'أيوه، سلّم',
    alreadySubmitted: 'الامتحان ده اتسلّم خلاص.',
    timeUpTitle: 'الوقت خلص',
    timeUpBody: 'امتحانك اتسلّم تلقائيًا.',
    graceRemaining: 'الوقت خلص — عندك {seconds} ثانية تسلّم فيهم.',
    checkAnswer: 'شوف الإجابة',
    correct: 'إجابة صحيحة',
    incorrect: 'إجابة خاطئة',
    partial: 'إجابة صح جزئيًا',
    needsGrading: 'محتاج تصحيح من المدرّس',
    notAnswered: 'مجاوبتش',
    yourAnswer: 'إجابتك',
    rightAnswer: 'الإجابة الصحيحة',
    explanation: 'الشرح',
    questionFeedback: 'ملاحظة على إجابتك',
    marksEarned: '{earned} من {max}',
    resultsTitle: 'نتيجتك',
    reviewTitle: 'مراجعة إجاباتك',
    reviewLocked: 'المراجعة مش متاحة دلوقتي',
    reviewLockedUntilClose: 'هتقدر تراجع إجاباتك بعد ما الامتحان يقفل.',
    passed: 'ناجح',
    failed: 'محتاج تحاول تاني',
    passMark: 'درجة النجاح {percent}%',
    retry: 'حاول تاني',
    cooldown: 'تقدر تحاول تاني بعد {hours} ساعة',
    noAttemptsLeft: 'خلصت محاولاتك في الامتحان ده',
    closed: 'الامتحان قفل',
    notOpenYet: 'الامتحان لسه مفتحش',
    notEnrolled: 'لازم تكون مشترك في الكورس عشان تدخل الامتحان',
    previousAttempts: 'محاولاتك السابقة',
    bestScore: 'أعلى درجة',
    essayPending: 'إجابتك المقالية عند المدرّس للتصحيح',
    wordCount: '{n} كلمة',
    typeAnswer: 'اكتب إجابتك',
    chooseOne: 'اختر إجابة واحدة',
    chooseMany: 'اختر كل الإجابات الصحيحة',
    true: 'صح',
    false: 'خطأ',
    /** The join/split delimiter between multiple option bodies in a
     *  right-answer/response summary (e.g. "أ، ب") — a formatting
     *  primitive, not a message, but still Arabic-locale punctuation and so
     *  lives here rather than as a bare literal in `apps/api`/`apps/web`. */
    answerListSeparator: '، ',
    blockedTitle: 'مينفعش تدخل الامتحان دلوقتي',
    scoreBandExcellent: 'أداء ممتاز',
    scoreBandGood: 'أداء كويس',
    scoreBandNeedsWork: 'محتاج تراجع الدرس تاني',
    reviewLockedDuringBody: 'هتقدر تراجع إجاباتك بعد ما تسلّم المحاولة.',
    unansweredChipLabel: 'سؤال {n}',
  },
  appeal: {
    open: 'قدّم تظلم',
    title: 'تظلم على الدرجة',
    note: 'اكتب سبب التظلم',
    notePlaceholder: 'وضّح ليه شايف إن الدرجة محتاجة مراجعة',
    submit: 'ابعت التظلم',
    submitted: 'وصلنا تظلمك، هنراجعه ونرد عليك',
    alreadyOpen: 'عندك تظلم مفتوح على السؤال ده',
    gradeBefore: 'الدرجة قبل التظلم',
    gradeAfter: 'الدرجة بعد التظلم',
    status: { open: 'مفتوح', under_review: 'تحت المراجعة', accepted: 'اتقبل', rejected: 'اترفض' },
    resolverNote: 'رد المدرّس',
    empty: 'مفيش تظلمات دلوقتي',
    queueTitle: 'التظلمات',
    resolve: 'اعتمد القرار',
    newMark: 'الدرجة الجديدة',
    accept: 'اقبل التظلم',
    reject: 'ارفض التظلم',
    columnStudent: 'الطالب',
    columnQuiz: 'الامتحان',
    columnQuestion: 'السؤال',
    columnNote: 'السبب',
    columnAge: 'قدّم من',
    filterAll: 'الكل',
    studentResponse: 'إجابة الطالب',
    modelAnswer: 'نموذج الإجابة',
    resolveFailed: 'مقدرناش نعتمد القرار — حاول تاني',
    resolved: 'اتحل التظلم',
  },
  quizAdmin: {
    bankTitle: 'بنك الأسئلة',
    newQuestion: 'سؤال جديد',
    editQuestion: 'تعديل السؤال',
    duplicate: 'نسخة من السؤال',
    duplicateSuffix: '(نسخة)',
    category: 'التصنيف',
    stem: 'نص السؤال',
    generalFeedback: 'الشرح بعد الإجابة',
    graderInfo: 'ملاحظات للمصحح',
    type: 'نوع السؤال',
    types: {
      mcq_single: 'اختيار من متعدد — إجابة واحدة',
      mcq_multi: 'اختيار من متعدد — أكتر من إجابة',
      true_false: 'صح أو خطأ',
      short_answer: 'إجابة قصيرة',
      essay: 'سؤال مقالي',
    },
    options: 'الاختيارات',
    addOption: 'أضف اختيار',
    removeOption: 'احذف الاختيار',
    markCorrect: 'الإجابة الصحيحة',
    optionFeedback: 'تعليق على الاختيار',
    fraction: 'وزن الاختيار',
    answerPattern: 'نموذج الإجابة',
    addPattern: 'أضف نموذج إجابة',
    caseSensitive: 'يفرّق بين الحروف الكبيرة والصغيرة',
    wildcardHint: 'استخدم * بدل أي جزء من الإجابة',
    defaultMark: 'درجة السؤال',
    minWords: 'أقل عدد كلمات',
    maxWords: 'أكبر عدد كلمات',
    save: 'احفظ',
    publish: 'انشر السؤال',
    published: 'السؤال اتنشر — أي تعديل بعد كده هيعمل نسخة جديدة',
    versionBadge: 'نسخة {n}',
    draftBadge: 'مسودة',
    bulkImport: 'استيراد سريع',
    bulkImportHint: 'الصق الأسئلة، كل سؤال في فقرة، وحدد الإجابة بسطر ANSWER أو الإجابة',
    bulkImportExample:
      'سؤال ١: عاصمة مصر إيه؟\nA. القاهرة\nB. الإسكندرية\nC. أسوان\nANSWER: A\n\n' +
      'سؤال ٢: النيل بيجري من الجنوب للشمال\nTYPE: true\nA. صح\nB. خطأ\nANSWER: A',
    bulkImportPreview: 'معاينة {n} سؤال',
    bulkImportCommit: 'أضف الأسئلة للبنك',
    quizTitle: 'إعدادات الامتحان',
    slots: 'أسئلة الامتحان',
    addSlot: 'أضف سؤال من البنك',
    addPool: 'أضف مجموعة عشوائية',
    poolPickCount: 'عدد الأسئلة المسحوبة',
    reorderHint: 'اسحب السؤال عشان تغيّر ترتيبه',
    mode: 'نوع الامتحان',
    durationMinutes: 'مدة الامتحان بالدقايق',
    gradeMethod: 'طريقة احتساب الدرجة عبر المحاولات',
    gradeMethodOptions: {
      highest: 'أعلى محاولة',
      average: 'متوسط المحاولات',
      first: 'أول محاولة',
      last: 'آخر محاولة',
    },
    openFromLabel: 'يفتح من',
    openUntilLabel: 'يقفل في',
    maxAttempts: 'أقصى عدد محاولات (٠ = غير محدود)',
    retryCooldownHours: 'المدة بين المحاولات بالساعات',
    passPercent: 'نسبة النجاح',
    shuffleQuestions: 'رتّب الأسئلة عشوائيًا',
    shuffleOptions: 'رتّب الاختيارات عشوائيًا',
    navMethod: 'التنقل بين الأسئلة',
    navFree: 'حر',
    navSequential: 'بالترتيب',
    overdueHandling: 'لما الوقت يخلص',
    overdueAutosubmit: 'يتسلّم تلقائيًا',
    overdueGrace: 'مهلة إضافية للتسليم',
    overdueAbandon: 'المحاولة تتلغي',
    graceSeconds: 'مهلة التسليم بالثواني',
    reviewMatrix: 'إيه اللي الطالب يشوفه',
    windows: {
      during: 'أثناء المحاولة',
      immediatelyAfter: 'بعد التسليم مباشرة',
      laterWhileOpen: 'بعد كده والامتحان مفتوح',
      afterClose: 'بعد ما الامتحان يقفل',
    },
    flags: {
      response: 'إجابته',
      correctness: 'صح ولا غلط',
      marks: 'الدرجات',
      specificFeedback: 'تعليق كل اختيار',
      generalFeedback: 'الشرح العام',
      rightAnswer: 'الإجابة الصحيحة',
      overallFeedback: 'تعليق النتيجة',
    },
    attemptsTitle: 'محاولات الطلاب',
    unlock: 'افتح المحاولة',
    reopen: 'ارجّع المحاولة للطالب',
    grantAttempt: 'امنح محاولة إضافية',
    grantTime: 'امنح وقت إضافي',
    grantTimeMinutes: 'دقايق إضافية',
    analyticsTitle: 'تحليل الامتحان',
    scoreDistribution: 'توزيع الدرجات',
    facilityIndex: 'معامل السهولة',
    discriminationIndex: 'معامل التمييز',
    distractorAnalysis: 'تحليل الاختيارات',
    attemptCount: '{n} محاولة',
    tooFewAttempts: 'محتاجين {n} محاولة على الأقل عشان الأرقام تبقى معبّرة',
    averageScore: 'متوسط الدرجات',
    medianScore: 'الوسيط',
    passRate: 'نسبة النجاح',
    newCategory: 'فئة جديدة',
    categoryNamePlaceholder: 'اسم الفئة',
    noCategories: 'مفيش فئات لسه — أضف واحدة',
    questionsEmpty: 'مفيش أسئلة في البنك لسه',
    search: 'دور بالنص...',
    searchQuestions: 'دور على سؤال...',
    shortcutsHint: 'Ctrl/⌘+Enter للحفظ — Escape للإغلاق — Enter في آخر اختيار يضيف اختيار جديد',
    showWeights: 'وزن الاختيار (متقدم)',
    publishQuiz: 'انشر الامتحان',
    slotsEmpty: 'مفيش أسئلة في الامتحان لسه',
    slotRemove: 'احذف السؤال من الامتحان',
    poolName: 'اسم المجموعة',
    poolPoints: 'درجة كل سؤال في المجموعة',
    columnQuestion: 'السؤال',
    columnN: 'عدد المحاولات',
    distractorPicks: '{n} اختار',
    columnStudent: 'الطالب',
    columnState: 'الحالة',
    columnScore: 'الدرجة',
    columnStarted: 'وقت البدء',
    columnDeadline: 'الموعد النهائي',
    columnActions: 'إجراءات',
    stateInProgress: 'شغال',
    stateOverdue: 'اتأخر',
    stateSubmitted: 'اتسلّم',
    statePendingReview: 'محتاج تصحيح',
    stateAbandoned: 'اتلغى',
    filterAll: 'الكل',
    searchStudent: 'دور بالاسم...',
    needsGradingOnly: 'محتاج تصحيح بس',
    confirmReopen: 'متأكد إنك عايز ترجّع المحاولة دي للطالب؟',
    extraSecondsLabel: 'ثواني إضافية',
    grantAttemptConfirm: 'امنح الطالب ده محاولة إضافية؟',
    actionSucceeded: 'اتنفّذ',
    actionFailed: 'مقدرناش ننفّذ الإجراء — حاول تاني',
  },
  quizErrors: {
    exactlyOneCorrect: 'لازم تحدد إجابة صحيحة واحدة بالظبط',
    atLeastTwoOptions: 'لازم يكون فيه اختيارين على الأقل',
    trueFalseNeedsTwo: 'سؤال صح وخطأ لازم يكون له اختيارين بالظبط',
    multiWeightsMustSumToOne: 'مجموع أوزان الإجابات الصحيحة لازم يساوي 1',
    multiNeedsPositive: 'لازم يكون فيه إجابة صحيحة واحدة على الأقل',
    shortAnswerNeedsFullCredit: 'لازم يكون فيه نموذج إجابة واحد على الأقل بوزن 1',
    patternRequired: 'اكتب نموذج الإجابة',
    patternTooLong: 'نموذج الإجابة طويل جدًا',
    tooManyWildcards: 'نموذج الإجابة فيه علامات * كتير جدًا',
    stemRequired: 'اكتب نص السؤال',
    optionBodyRequired: 'اكتب نص الاختيار',
    essayHasNoOptions: 'السؤال المقالي مالوش اختيارات',
    maxWordsBelowMin: 'أكبر عدد كلمات لازم يكون أكبر من أقل عدد',
    fractionRange: 'وزن الاختيار لازم يكون بين -1 و 1',
    importNoQuestions: 'مفيش أسئلة في النص ده',
    importNoAnswerLine: 'السؤال رقم {n}: مفيش سطر إجابة',
    importUnknownLetter: 'السؤال رقم {n}: حرف إجابة مش موجود ({letter})',
    importNoOptions: 'السؤال رقم {n}: مفيش اختيارات',
    importUnknownType: 'السؤال رقم {n}: نوع سؤال مش معروف',
  },
} as const;

export type Copy = typeof copy;
