/**
 * The single Arabic string table. No component may contain a user-facing literal.
 * This is what makes adding English later a routing change rather than a rewrite.
 */
export const copy = {
  site: {
    name: 'أيمن أبو العيلة',
    tagline: 'البرمجة وعلوم الحاسب — نظام البكالوريا المصرية',
    instructor: 'المهندس أيمن أبو العيلة',
  },
  nav: {
    home: 'الرئيسية',
    courses: 'الكورسات',
    about: 'عن المنصة',
    contact: 'تواصل معنا',
    login: 'تسجيل الدخول',
    register: 'حساب جديد',
    dashboard: 'حسابي',
  },
  theme: {
    toggle: 'تبديل المظهر',
    light: 'فاتح',
    dark: 'داكن',
    system: 'حسب النظام',
  },
  onboarding: {
    title: 'أكمل بيانات حسابك',
    subtitle: 'محتاجين شوية معلومات بسيطة عشان نظبطلك المنصة على مقاسك',
    step1Title: 'من إنت',
    step2Title: 'مكانك',
    step3Title: 'دراستك',
    optionalTitle: 'بيانات إضافية',
    optionalSubtitle: 'اختيارية دلوقتي، وهنفكرك بيها تاني بعد كده',
    fullName: 'الاسم الكامل',
    fullNamePlaceholder: 'اكتب اسمك بالكامل',
    gender: 'النوع',
    genderPlaceholder: 'اختر النوع',
    genderMale: 'ذكر',
    genderFemale: 'أنثى',
    genderError: 'اختر النوع',
    phone: 'رقم الهاتف',
    phonePlaceholder: '01012345678',
    governorate: 'المحافظة',
    governoratePlaceholder: 'اختر محافظتك',
    schoolName: 'اسم المدرسة',
    schoolNamePlaceholder: 'اختياري',
    system: 'النظام الدراسي',
    systemPlaceholder: 'اختر النظام الدراسي',
    year: 'الصف الدراسي',
    yearPlaceholder: 'اختر الصف الدراسي',
    track: 'المسار',
    trackPlaceholder: 'اختر المسار',
    electiveSubject: 'المادة الاختيارية',
    electiveSubjectPlaceholder: 'اختر المادة الاختيارية',
    fatherPhone: 'رقم هاتف الأب',
    motherPhone: 'رقم هاتف الأم',
    parentPhonePlaceholder: 'اختياري',
    skip: 'تخطي دلوقتي',
    skipHint: 'هنسألك تاني بعدين',
    undoSkip: 'إظهار الحقول',
    submit: 'حفظ ومتابعة',
    submitPending: 'جارٍ الحفظ…',
    submitError: 'تعذر حفظ بياناتك. تأكد منها وحاول تاني.',
    phoneConflictError: 'رقم الهاتف ده مسجل بحساب تاني بالفعل',
  },
  auth: {
    login: {
      title: 'تسجيل الدخول',
      subtitle: 'أهلًا بيك تاني، سجّل دخولك للمتابعة',
    },
    register: {
      title: 'إنشاء حساب جديد',
      subtitle: 'اعمل حسابك وابدأ رحلتك في البكالوريا المصرية',
    },
    fields: {
      name: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
    },
    actions: {
      login: 'تسجيل الدخول',
      loginPending: 'جارٍ تسجيل الدخول…',
      register: 'إنشاء حساب',
      registerPending: 'جارٍ إنشاء الحساب…',
    },
    switch: {
      noAccount: 'لسه معملتش حساب؟',
      createAccount: 'إنشاء حساب جديد',
      haveAccount: 'عندك حساب بالفعل؟',
      login: 'تسجيل الدخول',
    },
    providers: {
      divider: 'أو',
      google: 'المتابعة عبر جوجل',
      apple: 'المتابعة عبر أبل',
    },
    errors: {
      // One generic message per form, shown for EVERY failure reason on that
      // form (wrong password, unknown email, locked account, network error,
      // provider error). Never distinguish the cause in the UI — S1 requires
      // the login endpoint's responses to already be byte-identical across
      // failure modes, and a "helpful" UI message would quietly undo that by
      // reintroducing an enumeration signal one layer up.
      login: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      register: 'تعذر إنشاء الحساب. تأكد من البيانات وحاول تاني.',
    },
  },
  common: {
    loading: 'جارٍ التحميل',
    error: 'حصل خطأ',
    retry: 'حاول تاني',
    empty: 'مفيش حاجة هنا لسه',
  },
  settings: {
    devices: {
      title: 'أجهزتي',
      subtitle: 'الأجهزة اللي سجلت دخولك منها. تقدر تلغي أي جهاز مش عارفه.',
      current: 'الجهاز الحالي',
      loggedInAt: 'دخلت من هنا في',
      lastSeenAt: 'آخر نشاط',
      revoke: 'إلغاء الجهاز',
      revokePending: 'جارٍ الإلغاء…',
      revokeCurrentConfirm: 'ده الجهاز اللي بتستخدمه دلوقتي. لو ألغيته هتتسجل خروجك فورًا. متأكد؟',
      revokeError: 'تعذر إلغاء الجهاز. حاول تاني.',
      empty: 'مفيش أجهزة مسجلة دخول دلوقتي',
    },
  },
  home: {
    eyebrow: '01 / المنصة',
  },
  catalog: {
    eyebrow: '03 / الكورسات',
    title: 'الكورسات',
    subtitle: 'كل محاضرات البرمجة وعلوم الحاسب، مرتبة بالصف والمسار',
    empty: 'مفيش كورسات منشورة لسه',
    lessonCount: 'محاضرة',
    duration: 'المدة',
    minutes: 'دقيقة',
    hours: 'ساعة',
    freePreview: 'معاينة مجانية',
    free: 'مجاني',
    open: 'افتح الكورس',
  },
  course: {
    breadcrumbHome: 'الرئيسية',
    breadcrumbCatalog: 'الكورسات',
    content: 'محتوى الكورس',
    about: 'عن الكورس',
    instructor: 'المُحاضر',
    start: 'ابدأ الكورس',
    continue: 'كمّل الكورس',
    enrolled: 'إنت مشترك في الكورس ده',
    notFound: 'الكورس ده مش موجود',
    lessonKind: {
      video: 'فيديو',
      quiz: 'اختبار',
      attachment: 'مرفق',
      text: 'قراءة',
    },
  },
  admin: {
    nav: {
      dashboard: 'لوحة التحكم',
      content: 'المحتوى',
      courses: 'الكورسات',
    },
    common: {
      create: 'إضافة',
      save: 'حفظ',
      saving: 'جارٍ الحفظ',
      saved: 'اتحفظ',
      saveFailed: 'الحفظ فشل — التغييرات اترجعت زي ما كانت',
      cancel: 'إلغاء',
      delete: 'حذف',
      deleteConfirm: 'متأكد؟ الإجراء ده مش هيترجع.',
      required: 'الحقل ده مطلوب',
      publish: 'نشر',
    },
    course: {
      listTitle: 'الكورسات',
      new: 'كورس جديد',
      title: 'اسم الكورس',
      edit: 'تعديل الكورس',
      slug: 'المُعرّف في الرابط',
      slugHint: 'حروف إنجليزي صغيرة وأرقام وشرطات — ده اللي بيظهر في العنوان',
      subtitle: 'وصف مختصر',
      description: 'الوصف',
      system: 'النظام الدراسي',
      year: 'الصف الدراسي',
      track: 'المسار',
      trackNoneYear1: 'الصف الأول مالوش مسار',
      subject: 'المادة',
      status: 'الحالة',
      statusDraft: 'مسودة',
      statusPublished: 'منشور',
      statusArchived: 'مؤرشف',
      publish: 'نشر',
      unpublish: 'رجّعه مسودة',
      publishBlocked: 'لازم يكون فيه محاضرة منشورة واحدة على الأقل',
      empty: 'مفيش كورسات لسه',
    },
    section: {
      new: 'قسم جديد',
      title: 'اسم القسم',
      summary: 'نبذة',
      empty: 'مفيش أقسام لسه',
    },
    lesson: {
      new: 'محاضرة جديدة',
      title: 'عنوان المحاضرة',
      kind: 'النوع',
      freePreview: 'معاينة مجانية',
      estimatedSeconds: 'المدة التقديرية بالثواني',
      videoUrl: 'رابط يوتيوب',
      videoUrlHint: 'بناخد كود الفيديو (11 حرف) بس — الباقي بيتشال ومحدش بيفتح الرابط',
      videoUrlInvalid: 'الرابط ده مش رابط يوتيوب صالح',
      durationSeconds: 'مدة الفيديو بالثواني',
      body: 'محتوى الدرس',
      empty: 'مفيش محاضرات في القسم ده',
    },
    reorder: {
      hint: 'اسحب لإعادة الترتيب، أو استخدم زر المسافة والأسهم من الكيبورد',
      handle: 'مقبض السحب',
      pickedUp: 'اتمسكت المحاضرة في الترتيب رقم',
      movedOver: 'بقت في الترتيب رقم',
      dropped: 'اتسابت في الترتيب رقم',
      cancelled: 'اتلغى السحب والترتيب رجع زي ما كان',
    },
  },
} as const;

export type Copy = typeof copy;
